<?php $this->setSiteTitle('Charts'); ?>

<?php $this->start('head'); ?>
<?php $this->end(); ?>

<?php $this->start('body'); ?>
    <a href="index">Back</a><br>
    <h1>CSS Only Organization Chart Demo</h1>
            <ol class="organizational-chart">
                <li>
                    <div>
                        <h1>Primary</h1>
                    </div>
                    <div>
                        <h1>Primary</h1>
                    </div>
                    <div>
                        <h1>Primary</h1>
                    </div>
                    <ol>
                        <li>
                            <div>
                                <h2>Secondary</h2>
                            </div>
                            <ol>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                </li>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                    <ol>
                                        <li>
                                            <div>
                                                <h4>Quaternary</h4>
                                            </div>
                                        </li>
                                        <li>
                                            <div>
                                                <h4>Quaternary</h4>
                                            </div>
                                            <ol>
                                                <li>
                                                    <div>
                                                        <h5>Quinary</h5>
                                                    </div>
                                                </li>
                                                <li>
                                                    <div>
                                                        <h5>Quinary</h5>
                                                    </div>
                                                    <ol>
                                                        <li>
                                                            <div>
                                                                <h6>Senary</h6>
                                                            </div>
                                                        </li>
                                                    </ol>
                                                </li>
                                            </ol>
                                        </li>
                                        <li>
                                            <div>
                                                <h4>Quaternary</h4>
                                            </div>
                                        </li>
                                    </ol>
                                </li>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                </li>
                            </ol>
                        </li>
                        <li>
                            <div>
                                <h2>Secondary</h2>
                            </div>
                            <ol>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                </li>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                    <ol>
                                        <li>
                                            <div>
                                                <h4>Quaternary</h4>
                                            </div>
                                        </li>
                                        <li>
                                            <div>
                                                <h4>Quaternary</h4>
                                            </div>
                                        </li>
                                        <li>
                                            <div>
                                                <h4>Quaternary</h4>
                                            </div>
                                        </li>
                                    </ol>
                                </li>
                            </ol>
                        </li>
                        <li>
                            <div>
                                <h2>Secondary</h2>
                            </div>
                            <ol>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                    <ol>
                                        <li>
                                            <div>
                                                <h4>Quaternary</h4>
                                            </div>
                                            <ol>
                                                <li>
                                                    <div>
                                                        <h5>Quinary</h5>
                                                    </div>
                                                    <ol>
                                                        <li>
                                                            <div>
                                                                <h6>Senary</h6>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <div>
                                                                <h6>Senary</h6>
                                                            </div>
                                                        </li>
                                                    </ol>
                                                </li>
                                                <li>
                                                    <div>
                                                        <h5>Quinary</h5>
                                                    </div>
                                                </li>
                                            </ol>
                                        </li>
                                    </ol>
                                </li>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                </li>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                </li>
                            </ol>
                        </li>
                        <li>
                            <div>
                                <h2>Secondary</h2>
                            </div>
                            <ol>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                </li>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                </li>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                    <ol>
                                        <li>
                                            <div>
                                                <h4>Quaternary</h4>
                                            </div>
                                        </li>
                                        <li>
                                            <div>
                                                <h4>Quaternary</h4>
                                            </div>
                                        </li>
                                    </ol>
                                </li>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                </li>
                                <li>
                                    <div>
                                        <h3>Tertiary</h3>
                                    </div>
                                </li>
                            </ol>
                        </li>
                    </ol>
                </li>
            </ol>
<?php $this->end(); ?>
<?php $this->start('js-script'); ?>
<?php $this->end(); ?>
<?php $this->start('jquery'); ?>
<?php $this->end(); ?>
